### ISSUE TITLE
Validating set properties

### ISSUE THREAD

**Issue by stuarthendren** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#21]
Is there a way to validate the properties that are set?

It seems that the set properties are recorded in `InitialState` to the `recordedSetPropertyStates` but I don't think they are used in the `get` is there another way to access them for validation?

The nsubstitue library uses the `received` function, as below, but I don't think this works?  

```
var mode = calculator.Mode;
calculator.Mode = "TEST";
 
//Check received call to property getter
//We need to assign the result to a variable to keep
//the compiler happy.
var temp = calculator.Received().Mode;
 
//Check received call to property setter with arg of "TEST"
calculator.Received().Mode = "TEST";
```

**Comment by ffMathy** [comment]
That syntax should still work with substitute.js.

Isn't it working? Can you provide an example of where it doesn't work?

**Comment by stuarthendren** [comment]
I'm not sure I understand how that example converts to TypeScript, but all of these fail:

```
import { Substitute } from "@fluffy-spoon/substitute"
import * as assert from "assert"

interface Test {
  example: string
}

describe("Example Test", function() {
  it("Can do direct validation of set example", function() {
    const test = Substitute.for<Test>()
    test.example = "test"
    assert.ok(test.received().example === "test")
  })

  it("Can validate set example with get check first", function() {
    const test = Substitute.for<Test>()
    test.example = "test"
    let temp = test.received().example
    assert.equal(test.received().example, "test")
  })

  it("Can validate set example if had an inital value", function() {
    const test = Substitute.for<Test>()
    ;(<any>test).example.returns("initial")
    test.example = "test"
    let temp = test.received().example
    assert.equal(test.received().example, "test")
  })
})
```

Results in 

```
 Example Test
    1) Can do direct validation of set example
    2) Can validate set example with get check first
    3) Can validate set example if had an inital value


  0 passing (68ms)
  3 failing

  1) Example Test
       Can do direct validation of set example:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (src/base.test.ts:13:12)

  2) Example Test
       Can validate set example with get check first:
     AssertionError [ERR_ASSERTION]: undefined == 'test'
      at Context.<anonymous> (src/base.test.ts:20:12)

  3) Example Test
       Can validate set example if had an inital value:
     AssertionError [ERR_ASSERTION]: undefined == 'test'
      at Context.<anonymous> (src/base.test.ts:28:12)
```

**Comment by ffMathy** [comment]
Your syntax is wrong. Use it exactly like you do in Nsubstitute.

One equal sign instead of 3, and not wrapped in an assert call.

**Comment by stuarthendren** [comment]
Ah ok, thanks for your help. Just for reference if anyone else looks at this here is an example with a passing and failing test:

```TypeScript
import { Substitute } from "@fluffy-spoon/substitute"

interface Test {
  example: string
}

describe("Example Test", function() {
  it("Can do direct validation of set example", function() {
    const test = Substitute.for<Test>()
    test.example = "test"
    test.received().example = "test"
  })

  it("Should fail", function() {
    const test = Substitute.for<Test>()
    test.example = "test"
    test.received().example = "incorrect"
  })
})
```


Results:

```
  Example Test
    ✓ Can do direct validation of set example
    1) Should fail


  1 passing (67ms)
  1 failing

  1) Example Test
       Should fail:
     Error: Expected null calls to the property example with arguments ['test'], but received none of such calls.
All calls received to property example:
-> 1 call with arguments ['test']
      at InitialState.assertCallCountMatchesExpectations (node_modules/@fluffy-spoon/substitute/src/states/InitialState.ts:46:15)
      at SetPropertyState.set (node_modules/@fluffy-spoon/substitute/src/states/SetPropertyState.ts:44:30)
      at Context.set (node_modules/@fluffy-spoon/substitute/src/Context.ts:49:28)
      at Object.set (node_modules/@fluffy-spoon/substitute/src/Context.ts:22:22)
      at Context.<anonymous> (src/base.test.ts:17:28)

```

**Comment by ffMathy** [comment]
You're welcome. I'll re-open this, because I just realized the documentation around it is quite poor. I'll close as soon as I have updated the documentation.

Thanks for your feedback!

**Comment by ffMathy** [comment]
Updated documentation now.
