### ISSUE TITLE
Checking received calls seems to be off at times

### ISSUE THREAD

**Issue by sluebbert** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#45]
I seem to be running into an oddity when asserting that calls were made. The received method seems to be thrown off somehow based on the stripped down test shown below.

```
import { Substitute, Arg } from '@fluffy-spoon/substitute';

class Transaction
{
	public Id: number;
	public Description: string;

	constructor(id: number, description: string)
	{
		this.Id = id;
		this.Description = description;
	}
}

interface IDataAccess
{
	insertTransaction(transaction: Transaction): void;
	updateTransaction(transaction: Transaction): void;
}

class Manager
{
	private dataAccess: IDataAccess;

	constructor(dataAccess: IDataAccess)
	{
		this.dataAccess = dataAccess;
	}

	public run()
	{
		this.dataAccess.insertTransaction(new Transaction(1, 'milk'));
		this.dataAccess.updateTransaction(new Transaction(2, 'gas')); // Commenting out this line will cause the test to pass
	}
}

describe('Test', function()
{
	it('Tests', () =>
	{
		var dataAccess = Substitute.for<IDataAccess>();

		var manager = new Manager(dataAccess);
		manager.run();

		dataAccess.received().insertTransaction(Arg.is(x => x.Description == 'milk'));
	});
});
```
Running my test fails with the unexpected message:
```
$ ./node_modules/mocha/bin/mocha test.ts --require ts-node/register


  Test
    1) Tests


  0 passing (18ms)
  1 failing

  1) Test
       Tests:
     Error: Expected 1 or more calls to the method updateTransaction with arguments [Argument {
  description:
   "{predicate function (x) { return x.Description == 'milk'; }}",
  matchingFunction: [Function] }], but received none of such calls.
All calls received to method updateTransaction:
-> call with arguments [Transaction { Id: 2, Description: 'gas' }]
      at InitialState.assertCallCountMatchesExpectations (node_modules/@fluffy-spoon/substitute/src/states/InitialState.ts:46:15)
      at FunctionState.apply (node_modules/@fluffy-spoon/substitute/src/states/FunctionState.ts:48:30)
      at Context.apply (node_modules/@fluffy-spoon/substitute/src/Context.ts:45:28)
      at Object.apply (node_modules/@fluffy-spoon/substitute/src/Context.ts:19:29)
      at Context.<anonymous> (test.ts:48:25)
      at processImmediate (internal/timers.js:443:21)
```
The error message is complaining about the method updateTransaction, even though I only stated that I am interested in asserting that insertTransaction was called.  It does show the correct context of what really happened at runtime though, just with the wrong method.

**Comment by taylorn16** [comment]
I am experiencing the same issue. In my case it looks like this

```typescript
this.connection.start().then(() => this.connectionStarted$.next());
this.connection.onclose(() => this.connectionClosed$.next()); // commenting this line out makes the substitute behave normally
```

It seems a Substitute can't handle tracking more than one method being called on it during a test case?

**Comment by DanielSiepmann** [comment]
As far as I understood: 
The reason is, there is only context for the mock, not individual mocked methods. All methods share the same context, and reset the invocation counter on each invocation.
If one method of mock is invoked, everything is okay. If another one is invoked, the counter is reseted and is now at 1 again.

A failing test can be found here: https://github.com/DanielSiepmann/FluffySpoon.JavaScript.Testing.Faking/blob/bugfix/45-received-off/spec/issues/45.test.ts

**Comment by ffMathy** [comment]
@DanielSiepmann I see you made a repo for adding the broken test. Can you open a PR as well?

**Comment by IlhamKhabibullin** [comment]
So this issue is fixed now, after merging this pr https://github.com/ffMathy/FluffySpoon.JavaScript.Testing.Faking/pull/70

**Comment by ffMathy** [comment]
Thanks!
